### ISSUE TITLE
Writing to HDF5 with variable name

### ISSUE THREAD

**Issue by tlienart** [JuliaLang/HDF5.jl#269]
Hello, apologies if the question is somewhat naive,

What I'd like is:
```
my_write(file::HDF5file, variableContent, variableName)
```
to be called as
```
a = 5
my_write(file, a, "name")
```
is this possible?

Thanks

**Comment by ggggggggg** [comment]
`write(file,"name",a)` works. If you really want like that particular argument order you can define `my_write(f,a,name) = write(f,name,a)`, but I don't think thats actually a good idea. The documentation has some more examples.
