### ISSUE TITLE
read `dataset` in memory

### ISSUE THREAD

**Issue by jingpengwu** [JuliaLang/HDF5.jl#279]
It seems that `h5read` only created a link or view of h5 dataset.

I can use h5read to read dataset and list all the values. I can also plot the image using Gadfly.

But when I tried to write it to a svg file using Compose, it turns out that I can not see the image. The svg file shows `can not find the linked image`!

draw(SVG("output.svg", 3inch, 3inch), compose(context(), bitmap("image/png", Array{UInt8}(reshape( image_from_h5, 504*504)), 0, 0, 1, 1)))

when I read from tif file using `readall`, this code works. It only do not work with hdf5 file. So, I guess the problem is in the hdf5 reading part.

**Comment by timholy** [comment]
This seems rather unlikely to be the culprit. If you want to check yourself, you could try `img2 = copy(image_from_h5)` so that `img2` is not a link/view.

**Comment by jingpengwu** [comment]
Thanks for the response. I understand that this is quite unlikely. The type is the same and I also tried with same vector size. The copy also do not work... I'll close this issue.
