### ISSUE TITLE
Can read back a portion of a 2d array, but not of a 1d array

### ISSUE THREAD

**Issue by mwojnowicz** [JuliaLang/HDF5.jl#281]
As described in the documentation at https://github.com/JuliaLang/HDF5.jl, we can read back a portion of a  2d array:
    A = reshape(1:120, 15, 8)  #has type Array{Int64,2}
    h5write("/tmp/test2.h5", "mygroup2/A", A)
    data = h5read("/tmp/test2.h5", "mygroup2/A", (2:3:15, 3:5))

However, we cannot read back a portion of a 1d array:
    B=[1:10]   #has type Array{Int64,1}
    h5write("/tmp/test2.h5", "mygroup2/B", B)
    data = h5read("/tmp/test2.h5", "mygroup2/B", (1:5))

**Comment by ggggggggg** [comment]
Try
```
data = h5read("/tmp/test2.h5", "mygroup2/B", (1:5,))
```
It doesn't create a 1 element tuple without the trailing comma
```
julia> typeof((1:5))
UnitRange{Int64}

julia> typeof((1:5,))
Tuple{UnitRange{Int64}}
```

**Comment by mwojnowicz** [comment]
Ah, makes sense.  Thanks.
