### ISSUE TITLE
Store a Requests.Response to HDF5

### ISSUE THREAD

**Issue by femtotrader** [JuliaLang/HDF5.jl#296]
Hello,

I'm new to Julia. I'm a Python dev.
I'd like to be able to make a sort of cache mechanism of HTTP requests like [requests-cache](http://requests-cache.readthedocs.org/) 

see https://github.com/JuliaWeb/Requests.jl/issues/101

Ideally storing response to any kind of database (SQLite, MySQL, PostgreSQL...) will be nice but I haven't find an ORM like SQLAlchemy for Julia...

requests-cache is serializing response using [pickle](https://docs.python.org/3/library/pickle.html)

So I have been looking at serialization and Julia and found this SO question
http://stackoverflow.com/questions/24958248/julia-how-stable-are-serialize-deserialize

An answer point to https://github.com/JuliaLang/HDF5.jl so I'm trying HDF5.jl

Here is my code:

```
using Requests
using HDF5
resp = get("http://httpbin.org/get")
key = string(resp.request.value.uri)
h5open("cache.h5", "w") do file
    write(file, key, resp)
end
```

but it raises

```
ERROR: MethodError: `write` has no method matching write(::HDF5.HDF5File, ::ASCIIString, ::HttpCommon.Response)WARNING: Error showing method candidates, aborted
```

Any idea ?

Kind regards

PS: please excuse my newbie question!

**Comment by timholy** [comment]
HDF5 has been split into two package, the (new) HDF5 and JLD. You might try it with JLD.

**Comment by femtotrader** [comment]
Ok so I will have a look at https://github.com/JuliaLang/JLD.jl

**Comment by femtotrader** [comment]
I did

```
using Requests
using JLD
resp = get("http://httpbin.org/get")
key = string(resp.request.value.uri)
jldopen("cache.jld", "w") do file
    write(file, key, resp)  # alternatively, say "@write file A"
end


retrieved_resp = jldopen("cache.jld", "r") do file
    read(file, key)
end
```

it works fine...
but the path is still long to make a Requests-cache.jl library

If you know some people who could be interested in working on such a project please ping them...

Pinging some people for JuliaWeb: @malmaud @jrevels @MikeInnes @sbromberger @WestleyArgentum

**Comment by femtotrader** [comment]
Pinging also @reclosedev (author of requests-cache)

**Comment by malmaud** [comment]
You could always launch a squid server and set HTTP_PROXY to point to it - not sure it's worthwhile to reinvent that wheel in Julia.

**Comment by femtotrader** [comment]
I prefer to have a pure Julia solution. 

Here is my first implementation https://github.com/femtotrader/RequestsCache.jl

I'm planning to use it for https://github.com/femtotrader/DataReader.jl
