### ISSUE TITLE
No documentation in functions

### ISSUE THREAD

**Issue by UriAceves** [JuliaLang/HDF5.jl#299]
I'm deeply sorry, I'm using the example and I really dont get what is the second field in `h5write` for. I try to read the documentation but all it says is

```julia
HDF5.h5write is a generic Function.

# 1 method for generic function "h5write":
h5write(filename, name::ByteString, data)
```

Can anyone clarify to me what is "mygroup2/A" in the example and why it's needed 

```julia
A = reshape(1:120, 15, 8)
h5write("/tmp/test2.h5", "mygroup2/A", A)
data = h5read("/tmp/test2.h5", "mygroup2/A", (2:3:15, 3:5))
```

Again I'm sorry, I'm sure the answer is a triviality. 

Thank you very much.

**Comment by ggggggggg** [comment]
I think I understand your question, so I'll try to answer. An HDF5 file is like a mini file system, so you can store lots of data in one file, give the data paths that contain group (like folders) and names (like file names). The command `h5write("/tmp/test2.h5", "mygroup2/A", A)` can be read as: open the file `/tmp/test2.h5`, open (create if neccesary) the group `mygroup2` and make an entry called `A`, then write the contents of the variable `A` into there. You could run another command `h5write("/tmp/test2.h5", "mygroup2/B", B)` and your file would contain the data from both variables `A` and `B`. When you read from the file, you need to specify a path to read from.

Hope that helps. Please close the issue once your questions are resolved.

**Comment by UriAceves** [comment]
Thank you very much. I was having a weird error when trying to do `h5write("/tmp/test2.h5", "mygroup2/B", B)`, but I cant reproduce it, so it must have been me doing something wrong. 

Thanks for the explanation :smiley:
